### ISSUE TITLE
cryptic `TFLiteTensor.to_nx/2` error message when no Nx backend provided

### ISSUE THREAD

**Issue by mnishiguchi** [cocoa-xu/tflite_beam#32]
When `TFLiteTensor.to_nx/2` is called without Nx backend provided, a cryptic error can occur. I am wondering if there is a way to make this error less cryptic and/or to print a human friendly error message. 
 
https://hexdocs.pm/tflite_elixir/TFLiteElixir.TFLiteTensor.html#to_nx/2

The error seems to occur when `Nx.from_binary/3` is called.

https://hexdocs.pm/nx/Nx.html#from_binary/3

```
** (UndefinedFunctionError) function nil.from_binary/3 is undefined
    nil.from_binary(#Inspect.Error<
  got KeyError with message:

      """
      key :__struct__ not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
      """

  while inspecting:

      %{__struct__: Nx.Tensor, data: nil, names: [nil], shape: {100}, type: {:f, 32}}

  Stacktrace:

    (nx 0.5.1) lib/nx/tensor.ex:165: Inspect.Nx.Tensor.inspect/2
    (elixir 1.14.3) lib/inspect/algebra.ex:341: Inspect.Algebra.to_doc/2
    (elixir 1.14.3) lib/kernel.ex:2254: Kernel.inspect/2
    (elixir 1.14.3) lib/exception.ex:717: anonymous fn/2 in Exception.format_arity/1
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.14.3) lib/exception.ex:717: Exception.format_arity/1
    (elixir 1.14.3) lib/exception.ex:712: Exception.format_mfa/3
    (elixir 1.14.3) lib/exception.ex:623: Exception.format_stacktrace_entry/1

>, <<105, 9, 17, 64, 151, 171, 24, 191, 192, 69, 116, 62, 25, 75, 60, 63, 192, 10, 3, 192, 114, 80, 4, 63, 114, 80, 4, 64, 16, 4, 201, 63, 36, 209, 246, 63, 154, 234, 95, 191, 79, 52, 183, 190, 79, 52, 183, 190, 7, 189, ...>>, [])
    (tflite_elixir 0.1.5) lib/tflite_elixir/tflite_tensor.ex:124: TFLiteElixir.TFLiteTensor.to_nx/2
```

This error can be recreated just by removing `:backend` option in the [examples/artistic_style_transfer.livemd](https://github.com/cocoa-xu/tflite_elixir/blob/main/examples/artistic_style_transfer.livemd) notebook.

**Comment by cocoa-xu** [comment]
This should be better now. :)

```elixir
iex> alias TFLiteElixir.InterpreterBuilder
TFLiteElixir.InterpreterBuilder
iex> alias TFLiteElixir.Ops.Builtin.BuiltinResolver
TFLiteElixir.Ops.Builtin.BuiltinResolver
iex> alias TFLiteElixir.FlatBufferModel
TFLiteElixir.FlatBufferModel
iex> alias TFLiteElixir.Interpreter
TFLiteElixir.Interpreter
iex> alias TFLiteElixir.TFLiteTensor
TFLiteElixir.TFLiteTensor
iex> filename = Path.join([__DIR__, "test", "test_data", "mobilenet_v2_1.0_224_inat_bird_quant.tflite"])
"./test/test_data/mobilenet_v2_1.0_224_inat_bird_quant.tflite"
iex> model = FlatBufferModel.build_from_file(filename)
#FlatBufferModel<%{
  "initialized" => true,
  "metadata" => %{"TFLITE_METADATA" => <<28>>, "min_runtime_version" => "1.5.0"},
  "minimum_runtime" => "1.5.0"
}>
iex> resolver = BuiltinResolver.new!()
#Reference<0.331881720.996278283.169380>
iex> builder = InterpreterBuilder.new!(model, resolver)
#Reference<0.331881720.996278283.169392>
iex> interpreter = Interpreter.new!()
INFO: Initialized TensorFlow Lite runtime.
#Reference<0.331881720.996278283.169402>
iex> :ok = InterpreterBuilder.build!(builder, interpreter)
:ok
iex> :ok = Interpreter.allocate_tensors(interpreter)
:ok
iex> t = Interpreter.tensor(interpreter, 0)
%TFLiteElixir.TFLiteTensor{
  name: "map/TensorArrayStack/TensorArrayGatherV3",
  index: 0,
  shape: [1, 224, 224, 3],
  shape_signature: [1, 224, 224, 3],
  type: {:u, 8},
  quantization_params: %TFLiteElixir.TFLiteQuantizationParams{
    scale: [0.0078125],
    zero_point: [128],
    quantized_dimension: 0
  },
  sparsity_params: %{},
  reference: #Reference<0.331881720.996278283.169424>
}
iex> TFLiteTensor.to_nx(t)
#Nx.Tensor<
  u8[1][224][224][3]
  [
    [
      [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, ...],
        ...
      ],
      ...
    ]
  ]
>
iex> TFLiteTensor.to_nx(t, backend: nil)
#Nx.Tensor<
  u8[1][224][224][3]
  [
    [
      [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, ...],
        ...
      ],
      ...
    ]
  ]
>
iex> TFLiteTensor.to_nx(t, backend: Nx.BinaryBackend)
#Nx.Tensor<
  u8[1][224][224][3]
  [
    [
      [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, ...],
        ...
      ],
      ...
    ]
  ]
>
```

**Comment by cocoa-xu** [comment]
Hi @mnishiguchi, I also added tests for `TFLiteElixir.TFLiteTensor`, including improved error messages when `backend` is invalid. What do you think?

https://github.com/cocoa-xu/tflite_elixir/blob/d2a7cfb77cbc67dfc8ef324f74db0d10b2e308ec/test/tflitetensor_test.exs#L126-L194

**Comment by mnishiguchi** [comment]
Nice! The new error message is a lot less scary. Thank you!
